name: 'Identify changed OpenAPI files'
description: 'Lists the changed OpenAPI yaml files in a given subdirectory of the git workspace'
inputs:
  on-path:  
    description: 'filter for the subdirectory of the git workspace to scan'
    required: true
    default: 'openapi/**'
outputs:
  matrix:
    description: "GitHub Matrix in JSON format with changed files"
    value: ${{ steps.transform-to-matrix.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 2
    - run: echo Applying on path ${{ inputs.on-path }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - id: list-files
      run: $GITHUB_ACTION_PATH/list_changed_files.sh
      shell: bash
      env:
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        PREVIOUS_HASH: ${{ github.event.before }}
        CURRENT_HASH: ${{ github.event.after }}
        PATH_FILTER: ${{ inputs.on-path }}
    - id: transform-to-matrix
      run: $GITHUB_ACTION_PATH/transform_to_github_matrix.sh
      shell: bash
      env:
        CHANGED_FILES: ${{ steps.list-files.outputs.changed_files }}
