name: 'Identify changed OpenAPI files'
description: 'Lists the changed OpenAPI yaml files in a given subdirectory of the git workspace'
inputs:
  on-path:  
    description: 'filter for the subdirectory of the git workspace to scan'
    required: true
    default: 'openapi/**'
  path-filters:
    description: 'JSON array of strings representing path filter expressions, e.g. [\"openapi/**/*.yaml\", \"openapi/**/*.yml\"]'
    default: >
      ['openapi/**/*.yaml', 'openapi/**/*.yml']
outputs:
  matrix:
    description: "GitHub Matrix in JSON format with changed files"
    value: ${{ steps.transform-to-matrix.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Print path filters
      id: print-path-filters
      shell: bash
      run: |
        echo "$PATH_FILTERS"
      env: 
        PATH_FILTERS: ${{ fromJSON(inputs.path-filters) }} 
    - name: Identify changed OpenAPI files
      id: list-files
      run: $GITHUB_ACTION_PATH/list_changed_files.sh
      shell: bash
      env:
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        PREVIOUS_HASH: ${{ github.event.before }}
        CURRENT_HASH: ${{ github.event.after }}
        PATH_FILTER: ${{ inputs.on-path }}
    - name: Transform into GitHub matrix (special JSON format)
      id: transform-to-matrix
      run: $GITHUB_ACTION_PATH/transform_to_github_matrix.sh
      shell: bash
      env:
        CHANGED_FILES: ${{ steps.list-files.outputs.changed_files }}
